FROM gcc:latest

# env
ENV DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    TERM=xterm-256color \
    EDITOR=nvim

# 基本工具
RUN sed -i 's@http://deb.debian.org@http://mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    openssl \
    openssh-server \
    bash-completion \
    build-essential \
    busybox \
    cgdb \
    cmake \
    file \
    gdb \
    ninja-build \
    python-is-python3 \
    python3-venv \
    sudo \
    unzip \
    wget

# 配置与moderntools
RUN echo "\nif [ -f $HOME/.bash_aliases ]; then\n    . $HOME/.bash_aliases\nfi" >> $HOME/.bashrc \
    && echo "\nif [ -f $HOME/.bash_aliases_local ]; then\n    . $HOME/.bash_aliases_local\nfi" >> $HOME/.bashrc \
    && echo "\nif [ -f $HOME/.bash_env ]; then\n    . $HOME/.bash_env\nfi" >> $HOME/.bashrc \
    && echo '\nexport PS1="\[\e[32;1m\][\[\e[33;1m\]\u\[\e[31;1m\]@\[\e[33;1m\]\h \[\e[36;1m\]\w\[\e[32;1m\]]\[\e[34;1m\]\$ \[\e[0m\]"' >> $HOME/.bashrc \
    && echo 'export PATH="$HOME/.local/modernunix":${PATH}' >> $HOME/.bash_env \
    && echo 'export PATH="$HOME/.local/bin":${PATH}' >> $HOME/.bash_env \
    && echo "alias ls='lsd'" >> $HOME/.bash_aliases_local \
    && echo "alias vim='nvim'" >> $HOME/.bash_aliases_local \
    && echo "alias vi='/usr/bin/vim'" >> $HOME/.bash_aliases_local \
    && echo "alias gdb='cgdb -q'" >> $HOME/.bash_aliases_local \
    && echo "alias y='yazi'" >> $HOME/.bash_aliases_local \
    && echo "PermitRootLogin yes\nPasswordAuthentication no\nPubkeyAuthentication yes" >> /etc/ssh/sshd_config \
    && git clone https://gitee.com/kaikaixixi/.dotfiles.git $HOME/.dotfiles \
    && chmod +x $HOME/.dotfiles/run.sh \
    && cd $HOME/.dotfiles && ./run.sh \
    && git clone https://gitee.com/kaikaixixi/modernunix.git /tmp/modernunix \
    && mkdir -p $HOME/.local/modernunix \
    && find /tmp/modernunix -perm /111 -type f -not -path "*\.git*" -not -name "install.sh" -exec sudo cp {} $HOME/.local/modernunix/ \; \
    && ln -s $HOME/.local/modernunix/bazelisk /usr/bin/bazelisk \
    && ln -s $HOME/.dotfiles/scripts/bazel/bazel /usr/bin/bazel \
    && wget -O /tmp/node22.tar.xz https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz && tar xf /tmp/node22.tar.xz -C /opt \
    && wget -O /tmp/nvim11.4.tar.gz https://github.com/neovim/neovim/releases/download/v0.11.4/nvim-linux-x86_64.tar.gz && tar xf /tmp/nvim11.4.tar.gz -C /opt \
    && echo 'export PATH="/opt/node-v22.14.0-linux-x64/bin":${PATH}' >> $HOME/.bash_env \
    && echo 'export PATH="/opt/nvim-linux-x86_64/bin":${PATH}' >> $HOME/.bash_env \
    && apt-get clean && rm -rf /var/lib/apt/lists/*  /tmp/*

WORKDIR /workspace
CMD ["/bin/bash"]

