# Just ubuntu22.04 with some basic and useful tools, like g++ git bazel tmux uv etc
## You can get from https://raw.githubusercontent.com/captainwc/.dotfiles/refs/heads/main/scripts/docker/dockerfile-dev-base
FROM dev-base:latest

WORKDIR /workspace

RUN apt update && \
    apt install -y \
        pkg-config autoconf automake libcurl4-openssl-dev uuid-dev libncurses5-dev libtool python3-dev python3-pip libtiff-dev libeigen3-dev libsqlite3-dev sqlite3 && \
    python3 -m pip install protobuf==3.14.0 && \
    git clone --single-branch --branch v10.0.0 https://ghfast.top/https://github.com/minhanghuang/CyberRT.git && \
    cd CyberRT && \
    python3 install.py --proxy gitee && \
    sed "s|_SETUP_PATH=\$(cd \`dirname \$BASH_SOURCE\[0\]\`; pwd)|_SETUP_PATH=/workspace/CyberRT/install|g" /workspace/CyberRT/install/setup.bash > ~/setup_install.bash && \
    sed -e 's/@Python_VERSION@/3.10/g' \
        -e 's/_SETUP_PATH=\$(cd `dirname \$BASH_SOURCE\[0\]`; pwd)/_SETUP_PATH=\/workspace\/CyberRT\/build/g' \
        -e 's|source ${BUILD_PATH}/cyber_tools_auto_complete.bash|source /workspace/CyberRT/cyber/tools/cyber_tools_auto_complete.bash|g' \
        /workspace/CyberRT/setup.bash.in > ~/setup_build.bash && \
    apt clean && rm -rf /var/lib/apt/lists/*  /tmp/* && \
    echo "source ~/setup_install.bash" >> ~/.bash_env && \
    echo "source ~/setup_build.bash" >> ~/.bash_env && \
    echo -e "build-cyber:\n\tbash -c \"source install/setup.bash && mkdir -p build && cmake -B build -S . -G Ninja && cmake --build build --parallel 10\"" > makefile

WORKDIR /workspace/CyberRT
CMD [ "/bin/bash" ]

## Build images:
# docker build -t cyber-dev .
## Start Container:
# docker run -it --rm cyber-dev-latest:latest
