Index:
  Background: Build

CompileFlags:
  Add: [-xc++, -Wall, -std=c++20]
  Compiler: clang++

Diagnostics:
  ClangTidy:
    Add: ["*"]
    Remove: [
        abseil*,
        fuchsia*,
        llvmlib*,
        zircon*,
        altera*,
        google-readability-todo,
        readability-braces-around-statements,
        hicpp-braces-around-statements,
        modernize-use-trailing-return-type, # 不要每个都加上尾返回值类型
        readability-identifier-length, # 不检查变量名长度
        cppcoreguidelines-avoid-magic-numbers, # 不检查魔法数字
        readability-magic-numbers, #同上
        misc-no-recursion, #递归
        cppcoreguidelines-avoid-do-while,
        misc-non-private-member-variables-in-classes, # public成员变量，或许不该用，但是想用
        cppcoreguidelines-owning-memory, # 用gsl::owner<> 来表示指针拥有对象的所有权
        hicpp-avoid-c-arrays, # 禁用c风格数组
      ]
