# REF: https://yazi-rs.github.io/docs/configuration/yazi/
# Default: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[manager]
# ratio = [1, 2, 5]
ratio = [1, 2, 7]
show_hidden = true
show_symlink = true
linemode = "size"

[preview]
wrap = "no"
tab_size = 2

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'subl %*', orphan = true, desc = "sublime", for = "windows" },
    { run = 'code %*', orphan = true, desc = "vscode", for = "windows" },
]
