# REF: https://yazi-rs.github.io/docs/configuration/yazi/
# Default: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[manager]
ratio = [1, 2, 5]
show_hidden = true
linemode = "size"

[preview]
wrap = "yes"

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'subl %*', orphan = true, desc = "sublime", for = "windows" },
    { run = 'code %*', orphan = true, desc = "vscode", for = "windows" },
]
